name: Update Source

on:
  schedule:
    - cron: '0 6,18 * * *'
  workflow_dispatch:

env:
  GITHUB_REPOSITORY_EMAIL: ${{ secrets.REPO_EMAIL }}

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@main

#     - name: Update Source
#       run: |
#         git fetch
#         sh .github/update.sh || true

    - name: Clean Runs
      uses: actions/github-script@main
      id: clean
      with:
        script: |
          const { owner, repo, created_at } = context.repo;
          const { data: { workflow_runs=[] } } = await github.request('GET /repos/{owner}/{repo}/actions/runs', { owner, repo });
          const cleanRunsId = workflow_runs.map(run => (new Date().valueOf() - new Date(created_at).valueOf()) > 1000 * 3600 * 24);
          console.log(1000 * 3600 * 24);
          workflow_runs.forEach(run => {
            console.log((new Date().valueOf()) + '::::' + (new Date(created_at).valueOf()) + '::::' + (new Date().valueOf() - new Date(created_at).valueOf()))
          });
          console.log(cleanRunsId.length + '/' + workflow_runs.length);

    - name: Finish
      uses: actions/github-script@main
      id: check
      with:
        script: |
          const { owner, repo } = context.repo;
          if ("${{ env.UPDATED_SOURCE }}" == "true") {
            return 'continue';
          } else {
            console.log('Cancelling ...');
            const run_id = "${{ github.run_id }}";
            await github.rest.actions.cancelWorkflowRun({ owner, repo, run_id });
            return 'stop';
          }
        result-encoding: string

    # - name: SSH Connection to Actions
    #   uses: P3TERX/ssh2actions@v1.0.0
